server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxxxxx:3306/ubas?useSSL=false&serverTimezone=UTC
    username: root
    password: qweasd
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      host: xxxxxxx
      port: 6379
      database: 1
      connect-timeout: 500
      password:
    mongodb:
      uri: mongodb://paul:271891169@35.241.112.187:27017/userdata

mybatis-plus:
  type-aliases-package: com.datasystem.entity
